# Generated by Django 3.1.1 on 2020-09-30 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0004_characters_char_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 39, 40, 796494), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 39, 40, 796523), verbose_name='date updated'),
        ),
    ]
