# Generated by Django 3.1.1 on 2020-09-30 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0005_auto_20200930_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 43, 0, 882292), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 43, 0, 882325), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='usercharacters',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 43, 0, 886426), verbose_name='date added'),
        ),
    ]
