# Generated by Django 3.1.1 on 2020-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0007_auto_20200930_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
