# Generated by Django 3.1.1 on 2020-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0008_characters_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='avaliable_comics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
