# Generated by Django 3.1.1 on 2020-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0009_auto_20200930_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacters',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
