# Generated by Django 3.1.1 on 2020-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0010_usercharacters_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharacters',
            name='char_user_alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
